
Use proyectoE
Go

Insert Into Rol(idRol, rol, descripcion)
Values (2, 'Usuario', 'Persona que usa la aplicacion web')
Go

Insert Into Usuario(dpi, nombre, correo, telefono, idRol, contrasena)
Values(2995988530101, 'Carlos Leal', 'carlealp@gmail.com', '34836528', 2, 'carlealp')
Go

Insert Into Departamento(nombre) Values
	('Alta Verapaz')
    ,('Baja Verapaz')
    ,('ChimaltenanGo')
    ,('Chiquimula')
    ,('El Progreso')
    ,('Escuintla')
    ,('Guatemala')
    ,('HuehuetenanGo')
    ,('Izabal')
    ,('Jalapa')
    ,('Jutiapa')
    ,('Petén')
    ,('QuetzaltenanGo')
    ,('Quiché')
    ,('Retalhuleu')
    ,('Sacatepéquez')
    ,('San Marcos')
    ,('Santa Rosa')
    ,('Solola')
    ,('Suchitepéquez')
    ,('Totonicapán')
    ,('Zacapa')
Go

Insert Into Municipio(idDepartamento,nombre) Values
	(1, 'Chahal'),
	(1, 'Chisec'),
    (1, 'Cobán'),
    (1, 'Fray Bartolomé de las Casas'),
    (1, 'La Tinta'),
    (1, 'Lanquín'),
    (1, 'Panzós'),
    (1, 'Raxruhá'),
    (1, 'San Cristóbal Verapaz'),
    (1, 'San Juan Chamelco'),
    (1, 'San Pedro Carchá'),
    (1, 'Santa Cruz Verapaz'),
    (1, 'Santa María Cahabón'),
    (1, 'Senahú'),
    (1, 'Tamahú'),
    (1, 'Tactic'),
    (1, 'Tucurú'),
	(2, 'Cubulco'),
    (2, 'Granados'),
    (2, 'Purulhá'),
    (2, 'Rabinal'),
    (2, 'Salamá'),
    (2, 'San Jerónimo'),
    (2, 'San Miguel Chicaj'),
    (2, 'Santa Cruz el Chol'),
	(3, 'AcatenanGo'),
    (3, 'ChimaltenanGo'),
    (3, 'El Tejar'),
    (3, 'Parramos'),
    (3, 'Patzicía'),
    (3, 'Patzún'),
    (3, 'Pochuta'),
    (3, 'San Andrés Itzapa'),
    (3, 'San José Poaquíl'),
    (3, 'San Juan Comalapa'),
    (3, 'San Martín Jilotepeque'),
    (3, 'Santa Apolonia'),
    (3, 'Santa Cruz Balanyá'),
    (3, 'Tecpán'),
    (3, 'Yepocapa'),
    (3, 'ZaraGoza'),
	(4, 'Camotán'),
    (4, 'Chiquimula'),
    (4, 'Concepción Las Minas'),
    (4, 'Esquipulas'),
    (4, 'Ipala'),
    (4, 'Jocotán'),
    (4, 'Olopa'),
    (4, 'Quezaltepeque'),
    (4, 'San Jacinto'),
    (4, 'San José la Arada'),
    (4, 'San Juan Ermita'),
	(5, 'El Jícaro'),
    (5, 'Guastatoya'),
    (5, 'Morazán'),
    (5, 'San Agustín Acasaguastlán'),
    (5, 'San Antonio La Paz'),
    (5, 'San Cristóbal Acasaguastlán'),
    (5, 'Sanarate'),
    (5, 'Sansare'),
	(6, 'Escuintla'),
    (6, 'Guanagazapa'),
    (6, 'Iztapa'),
    (6, 'La Democracia'),
    (6, 'La Gomera'),
    (6, 'Masagua'),
    (6, 'Nueva Concepción'),
    (6, 'Palín'),
    (6, 'San José'),
    (6, 'San Vicente Pacaya'),
    (6, 'Santa Lucía Cotzumalguapa'),
    (6, 'Siquinalá'),
    (6, 'Tiquisate'),
	(7, 'Amatitlán'),
    (7, 'Chinautla'),
    (7, 'Chuarrancho'),
    (7, 'Guatemala'),
    (7, 'Fraijanes'),
    (7, 'Mixco'),
    (7, 'Palencia'),
    (7, 'San José del Golfo'),
    (7, 'San José Pinula'),
    (7, 'San Juan Sacatepéquez'),
    (7, 'San Miguel Petapa'),
    (7, 'San Pedro Ayampuc'),
    (7, 'San Pedro Sacatepéquez'),
    (7, 'San Raymundo'),
    (7, 'Santa Catarina Pinula'),
    (7, 'Villa Canales'),
    (7, 'Villa Nueva'),
	(8, 'Aguacatán'),
    (8, 'Chiantla'),
    (8, 'ColotenanGo'),
    (8, 'Concepción Huista'),
    (8, 'Cuilco'),
    (8, 'HuehuetenanGo'),
    (8, 'JacaltenanGo'),
    (8, 'La Democracia'),
    (8, 'La Libertad'),
    (8, 'Malacatancito'),
    (8, 'Nentón'),
    (8, 'San Antonio Huista'),
    (8, 'San Gaspar Ixchil'),
    (8, 'San Ildefonso Ixtahuacán'),
    (8, 'San Juan Atitán'),
    (8, 'San Juan Ixcoy'),
    (8, 'San Mateo Ixtatán'),
    (8, 'San Miguel Acatán'),
    (8, 'San Pedro Nécta'),
    (8, 'San Pedro Soloma'),
    (8, 'San Rafael La Independencia'),
    (8, 'San Rafael Pétzal'),
    (8, 'San Sebastián Coatán'),
    (8, 'San Sebastián HuehuetenanGo'),
    (8, 'Santa Ana Huista'),
    (8, 'Santa Bárbara'),
    (8, 'Santa Cruz Barillas'),
    (8, 'Santa Eulalia'),
    (8, 'SantiaGo ChimaltenanGo'),
    (8, 'Tectitán'),
    (8, 'Todos Santos Cuchumatán'),
    (8, 'Unión Cantinil'),
	(9, 'El Estor'),
    (9, 'Livingston'),
    (9, 'Los Amates'),
    (9, 'Morales'),
    (9, 'Puerto Barrios'),
	(10, 'Jalapa'),
    (10, 'Mataquescuintla'),
    (10, 'Monjas'),
    (10, 'San Carlos Alzatate'),
    (10, 'San Luis Jilotepeque'),
    (10, 'San Manuel Chaparrón'),
    (10, 'San Pedro Pinula'),
	(11, 'Agua Blanca'),
    (11, 'Asunción Mita'),
    (11, 'Atescatempa'),
    (11, 'Comapa'),
    (11, 'Conguaco'),
    (11, 'El Adelanto'),
    (11, 'El Progreso'),
    (11, 'Jalpatagua'),
    (11, 'Jerez'),
    (11, 'Jutiapa'),
    (11, 'Moyuta'),
    (11, 'Pasaco'),
    (11, 'Quesada'),
    (11, 'San José Acatempa'),
    (11, 'Santa Catarina Mita'),
    (11, 'Yupiltepeque'),
    (11, 'Zapotitlán'),
	(12, 'Dolores'),
    (12, 'El Chal'),
    (12, 'Ciudad Flores'),
    (12, 'La Libertad'),
    (12, 'Las Cruces'),
    (12, 'Melchor de Mencos'),
    (12, 'Poptún'),
    (12, 'San Andrés'),
    (12, 'San Benito'),
    (12, 'San Francisco'),
    (12, 'San José'),
    (12, 'San Luis'),
    (12, 'Santa Ana'),
    (12, 'Sayaxché'),
	(13, 'Almolonga'),
    (13, 'Cabricán'),
    (13, 'Cajolá'),
    (13, 'Cantel'),
    (13, 'Coatepeque'),
    (13, 'Colomba Costa Cuca'),
    (13, 'Concepción Chiquirichapa'),
    (13, 'El Palmar'),
    (13, 'Flores Costa Cuca'),
    (13, 'Génova'),
    (13, 'Huitán'),
    (13, 'La Esperanza'),
    (13, 'Olintepeque'),
    (13, 'Palestina de Los Altos'),
    (13, 'QuetzaltenanGo'),
    (13, 'Salcajá'),
    (13, 'San Carlos Sija'),
    (13, 'San Francisco La Unión'),
    (13, 'San Juan Ostuncalco'),
    (13, 'San Martín Sacatepéquez'),
    (13, 'San Mateo'),
    (13, 'San Miguel Sigüilá'),
    (13, 'Sibilia'),
    (13, 'Zunil'),
	(14, 'Canillá'),
    (14, 'Chajul'),
    (14, 'Chicamán'),
    (14, 'Chiché'),
    (14, 'ChichicastenanGo'),
    (14, 'Chinique'),
    (14, 'Cunén'),
    (14, 'Ixcán Playa Grande'),
    (14, 'Joyabaj'),
    (14, 'Nebaj'),
    (14, 'Pachalum'),
    (14, 'Patzité'),
    (14, 'Sacapulas'),
    (14, 'San Andrés Sajcabajá'),
    (14, 'San Antonio IlotenanGo'),
    (14, 'San Bartolomé JocotenanGo'),
    (14, 'San Juan Cotzal'),
    (14, 'San Pedro Jocopilas'),
    (14, 'Santa Cruz del Quiché'),
    (14, 'Uspantán'),
    (14, 'Zacualpa'),
	(15, 'Champerico'),
    (15, 'El Asintal'),
    (15, 'Nuevo San Carlos'),
    (15, 'Retalhuleu'),
    (15, 'San Andrés Villa Seca'),
    (15, 'San Felipe Reu'),
    (15, 'San Martín Zapotitlán'),
    (15, 'San Sebastián'),
    (15, 'Santa Cruz Muluá'),
	(16, 'AlotenanGo'),
    (16, 'Ciudad Vieja'),
    (16, 'JocotenanGo'),
    (16, 'Antigua Guatemala'),
    (16, 'Magdalena Milpas Altas'),
    (16, 'Pastores'),
    (16, 'San Antonio Aguas Calientes'),
    (16, 'San Bartolomé Milpas Altas'),
    (16, 'San Lucas Sacatepéquez'),
    (16, 'San Miguel Dueñas'),
    (16, 'Santa Catarina Barahona'),
    (16, 'Santa Lucía Milpas Altas'),
    (16, 'Santa María de Jesús'),
    (16, 'SantiaGo Sacatepéquez'),
    (16, 'Santo DominGo Xenacoj'),
    (16, 'SumpanGo'),
	(17, 'Ayutla'),
    (17, 'Catarina'),
    (17, 'Comitancillo'),
    (17, 'Concepción Tutuapa'),
    (17, 'El Quetzal'),
    (17, 'El Tumbador'),
    (17, 'Esquipulas Palo Gordo'),
    (17, 'Ixchiguán'),
    (17, 'La Blanca'),
    (17, 'La Reforma'),
    (17, 'Malacatán'),
    (17, 'Nuevo Progreso'),
    (17, 'Ocós'),
    (17, 'Pajapita'),
    (17, 'Río Blanco'),
    (17, 'San Antonio Sacatepéquez'),
    (17, 'San Cristóbal Cucho'),
    (17, 'San José El Rodeo'),
    (17, 'San José Ojetenam'),
    (17, 'San Lorenzo'),
    (17, 'San Marcos'),
    (17, 'San Miguel Ixtahuacán'),
    (17, 'San Pablo'),
    (17, 'San Pedro Sacatepéquez'),
    (17, 'San Rafael Pie de la Cuesta'),
    (17, 'Sibinal'),
    (17, 'Sipacapa'),
    (17, 'Tacaná'),
    (17, 'Tajumulco'),
    (17, 'Tejutla'),
	(18, 'Barberena'),
    (18, 'Casillas'),
    (18, 'Chiquimulilla'),
    (18, 'Cuilapa'),
    (18, 'Guazacapán'),
    (18, 'Nueva Santa Rosa'),
    (18, 'Oratorio'),
    (18, 'Pueblo Nuevo Viñas'),
    (18, 'San Juan Tecuaco'),
    (18, 'San Rafael las Flores'),
    (18, 'Santa Cruz Naranjo'),
    (18, 'Santa María Ixhuatán'),
    (18, 'Santa Rosa de Lima'),
    (18, 'Taxisco'),
	(19, 'Concepción'),
    (19, 'Nahualá'),
    (19, 'Panajachel'),
    (19, 'San Andrés Semetabaj'),
    (19, 'San Antonio Palopó'),
    (19, 'San José Chacayá'),
    (19, 'San Juan La Laguna'),
    (19, 'San Lucas Tolimán'),
    (19, 'San Marcos La Laguna'),
    (19, 'San Pablo La Laguna'),
    (19, 'San Pedro La Laguna'),
    (19, 'Santa Catarina Ixtahuacán'),
    (19, 'Santa Catarina Palopó'),
    (19, 'Santa Clara La Laguna'),
    (19, 'Santa Cruz La Laguna'),
    (19, 'Santa Lucía Utatlán'),
    (19, 'Santa María Visitación'),
    (19, 'SantiaGo Atitlán'),
    (19, 'Sololá'),
	(20, 'Chicacao'),
    (20, 'CuyotenanGo'),
    (20, 'MazatenanGo'),
    (20, 'Patulul'),
    (20, 'Pueblo Nuevo'),
    (20, 'Río Bravo'),
    (20, 'Samayac'),
    (20, 'San Antonio Suchitepéquez'),
    (20, 'San Bernardino'),
    (20, 'San Francisco Zapotitlán'),
    (20, 'San Gabriel'),
    (20, 'San José El Idolo'),
    (20, 'San José La Maquina'),
    (20, 'San Juan Bautista'),
    (20, 'San Lorenzo'),
    (20, 'San Miguel Panán'),
    (20, 'San Pablo Jocopilas'),
    (20, 'Santa Bárbara'),
    (20, 'Santo DominGo Suchitepéquez'),
    (20, 'Santo Tomás La Unión'),
    (20, 'Zunilito'),
	(21, 'MomostenanGo'),
    (21, 'San Andrés Xecul'),
    (21, 'San Bartolo'),
    (21, 'San Cristóbal Totonicapán'),
    (21, 'San Francisco El Alto'),
    (21, 'Santa Lucía La Reforma'),
    (21, 'Santa María Chiquimula'),
    (21, 'Totonicapán'),
	(22, 'Cabañas'),
    (22, 'Estanzuela'),
    (22, 'Gualán'),
    (22, 'Huité'),
    (22, 'La Unión'),
    (22, 'Río Hondo'),
    (22, 'San DieGo'),
    (22, 'San Jorge'),
    (22, 'Teculután'),
    (22, 'Usumatlán'),
    (22, 'Zacapa')
Go

Insert Into sectorEmpresa(idSector, Nombre) values 
	(1,'Servicios'),
	(2,'Comercio'),
	(3,'Agroindustria'),
	(4,'Industria'),
	(5,'Manufactura Ligera'),
	(6,'Muebles'),
	(7,'Tecnología')
Go